USE [master]
GO

/****** Object:  Database [QLBD]    Script Date: 12/17/2022 2:38:07 AM ******/
CREATE DATABASE [QLBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLBD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLBD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLBD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLBD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLBD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLBD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QLBD] SET  MULTI_USER 
GO

ALTER DATABASE [QLBD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLBD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLBD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLBD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QLBD] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QLBD] SET  READ_WRITE 
GO

